name: Deploy Website

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: master
          path: src
      - name: Check out deploy branch
        uses: actions/checkout@v4
        with:
          ref: deploy
          path: deploy
      - name: Clean up output
        run: |
          find . -mindepth 1 -maxdepth 1 -not -name '.git' -print0 | xargs -0 rm -rf
        working-directory: deploy
      - name: Set up dependencies
        run: npm install
        working-directory: src
      - name: Build website
        run: npm run build:website
        working-directory: src
      - name: Copy website
        run: cp -r src/website/. deploy/
      - name: Commit result
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "deploy: website ${{ github.run_id }}"
          fi
          git push
        working-directory: deploy
