name: Test

on:
  push:
    branches: '**'
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build (Node 16)
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Initialize Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

  nodes:
    name: Build (Node 14 & 17)
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 17]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Initialize Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
    
  test:
    name: Testing and Linting
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Initialize Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install Dependencies
        run: npm install

      - name: Test (without coverage)
        run: npm run test      
      - name: Lint
        run: npm run lint

  coveralls:
    name: Report to Coveralls
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Initialize Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install Dependencies
        run: npm install

      - name: Test (with coverage)
        run: npm run test:nyc
      - name: Configure Coveralls
        run: 'echo "repo_token: $COVERALLS_REPO_TOKEN" > .coveralls.yml'
        shell: bash
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
      - name: Report Coverage
        run: npm run coverage

  analyze:
    name: CodeQL (GitHub)
    needs: build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    # strategy:
    #   fail-fast: false
    #   matrix:
    #     language: [ 'javascript' ]
    #     # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
    #     # Learn more about CodeQL language support at https://git.io/codeql-language-support

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: 'javascript'
        # If you wish to specify custom queries, you can do so here or in a config file.
        # By default, queries listed here will override any specified in a config file.
        # Prefix the list here with "+" to use these queries and those in the config file.
        # queries: ./path/to/local/query, your-org/your-repo/queries@main
